version: '3'
services:
  connector-abuseipdb-ipblacklist:
    image: THREATLENS/connector-abuseipdb-ipblacklist:6.4.8
    environment:
      - THREATLENS_URL=http://THREATLENS:8080
      - THREATLENS_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe # Valid UUIDv4
      - "CONNECTOR_NAME=AbuseIPDB IP Blacklist"
      - CONNECTOR_SCOPE=abuseipdb
      - CONNECTOR_LOG_LEVEL=error
      - ABUSEIPDB_URL=https://api.abuseipdb.com/api/v2/blacklist
      - ABUSEIPDB_API_KEY=ChangeMe
      - ABUSEIPDB_SCORE=100
      - ABUSEIPDB_LIMIT=10000
      - ABUSEIPDB_INTERVAL=2 #Day
    restart: always
