version: '3'
services:
  connector-abuse-ssl:
    image: THREATLENS/connector-abuse-ssl:6.4.8
    environment:
      - THREATLENS_URL=http://THREATLENS:8080
      - THREATLENS_TOKEN=CHANGEME
      - CONNECTOR_ID=CHANGEME_UUID4
      - "CONNECTOR_NAME=Abuse.ch SSL Blacklist"
      - CONNECTOR_SCOPE=abusessl
      - CONNECTOR_LOG_LEVEL=error
      - ABUSESSL_URL=https://sslbl.abuse.ch/blacklist/sslipblacklist.csv
      - ABUSESSL_INTERVAL=360 # Time to wait in minutes between subsequent requests
    restart: always
