version: '3'
services:
  connector-anyrun-feed:
    image: THREATLENS/connector-anyrun-feed:6.4.8
    environment:
      - THREATLENS_URL=http://THREATLENS:8080
      - THREATLENS_TOKEN=CHANGME
      - CONNECTOR_ID=CHANGEME
      - CONNECTOR_NAME=ANY.RUN feed
      - CONNECTOR_SCOPE=stix2
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_RUN_EVERY=1d
      - ANYRUN_TI_TOKEN=ChangeMe # Required
    restart: always
